import business.AuthenticationKeywords as AuthenticationKeywords
import business.ProductKeywords as ProductKeywords

AuthenticationKeywords.loginAsStandardUser()

ProductKeywords.verifyBackpackDetailsAndAddToCart()