import business.AuthenticationKeywords
import business.ProductKeywords
import business.CartKeywords
AuthenticationKeywords.loginAsStandardUser()
ProductKeywords.addBackpackFromInventory()
CartKeywords.removeBackpackAndContinueShopping()
